### ISSUE TITLE
backend test

### ISSUE THREAD

**Issue by hdrdavies** [kat4/map4#16]
The first one is jokes.

https://github.com/kat4/map4/blob/master/tests/servertests.js#L6

Also, your more important functions are being tested properly, which I'm sure you know.

Do be careful to avoid pushing commented code to master. Master should be super clean!

**Comment by mantagen** [comment]
True.

Oh well, can't reverse time. Will try to do this better next time.

Please to close this issue if you feel it requires no further action :)
:8ball:

**Comment by hdrdavies** [comment]
I expect loooooooooots of tests next week xoxox :eggplant:
