### ISSUE TITLE
Choice of variable naming?

### ISSUE THREAD

**Issue by hdrdavies** [kat4/map4#18]
https://github.com/kat4/map4/blob/master/public/js/frontend.js#L34

**Comment by katkelemen** [comment]
:eggplant:

**Comment by mantagen** [comment]
I can't tell if this is an immature comment, or if you've forgotten about cum freq?

http://lmgtfy.com/?q=cum+freq

**Comment by hdrdavies** [comment]
what about: 

 var timeStepsCumul 

:eggplant:

**Comment by katpas** [comment]
Hi @hdrdavies , in this code that variable is short for cumulative. Sorry for any mis-underdstanding. Please close.

**Comment by hdrdavies** [comment]
not happy, but I'll close
