### ISSUE TITLE
Train jumps around?

### ISSUE THREAD

**Issue by hdrdavies** [kat4/map4#22]
On the heroku app

https://www.youtube.com/watch?v=KZaz7OqyTHQ

**Comment by Joshua-Ronan-Phillips** [comment]
It jumps due to TFL's data not being accurate. Not much we can do about that :(

**Comment by mantagen** [comment]
Please close the issue

**Comment by katpas** [comment]
I would also like it if you closed this issue

**Comment by mantagen** [comment]
Please do close this if you feel it requires no further action :)

**Comment by Joshua-Ronan-Phillips** [comment]
For the love of code! Close the issue mate!

**Comment by hdrdavies** [comment]
:eggplant: :eggplant: :eggplant: :eggplant: :eggplant: :eggplant: :eggplant:

**Comment by hdrdavies** [comment]
Would have liked a comment from Kata
